/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    IBiArrowBarLeft: typeof import('~icons/bi/arrow-bar-left')['default']
    IBiArrowBarRight: typeof import('~icons/bi/arrow-bar-right')['default']
    IBiPencilSquare: typeof import('~icons/bi/pencil-square')['default']
    IBiTaxiFront: typeof import('~icons/bi/taxi-front')['default']
    IBiTrash3: typeof import('~icons/bi/trash3')['default']
    IconCustom: typeof import('./src/components/IconCustom/IconCustom.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
